[package]
name = "csvtutor"
version = "0.1.0"
edition = "2021"

[dependencies]
csv="1.3"
plotters = "0.3.7"
serde = { version = "1.0.217", features = ["derive"] }
chrono = "0.4"
rust_decimal = "1.36.0"
